gatewayClass:
  name: istio

gateway:
  namespace: istio-gateway
  name: gateway
  httpListener: 
    name: http-listener
    hostname: "*.par.sandboxcloud.xyz"
    port: 80
  httpsListener:
    pathBased:
      name: api-https-listener
      hostname: api.par.sandboxcloud.xyz
      port: 443
      certificateRef: "par-api-cert"
      pathUrls:
        nginx: /nginx
        httpbin: /httpbin
        helloServer: /hello
    domainBased:
      nginx:
        name: nginx-https-listener
        hostname: api.nginx.par.sandboxcloud.xyz
        port: 443
        certificateRef: "nginx-cert"
        routeName: nginx-route
      httpbin:
        name: httpbin-https-listener
        hostname: api.httpbin.par.sandboxcloud.xyz
        port: 443
        certificateRef: "httpbin-cert"
        routeName: httpbin-route
      helloServer:
        name: hello-server-https-listener
        hostname: api.hello.par.sandboxcloud.xyz
        port: 443
        certificateRef: "hello-server-cert"
        routeName: hello-server-route

apps:
  nginx:
    name: nginx
    replicas: 1
    service:
      name: nginx
    image: 
      name: nginx
      tag: latest
    portData:
      port: 8000
      targetPort: 80
  httpbin:
    name: httpbin
    replicas: 1
    service:
      name: httpbin
    image: 
      name: docker.io/kong/httpbin
      tag: latest
    portData:
      port: 8001
      targetPort: 80
  helloServer:
    name: hello-server
    replicas: 2
    service:
      name: hello-server
    image: 
      name: amixxdu/hello-node-server
      tag: 2.0.0
    portData:
      port: 8002
      targetPort: 3001

certificateManager:
  clusterIssuer: production-cluster-issuer