apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.helloServer.name }}
spec:
  replicas: {{ .Values.apps.helloServer.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.apps.helloServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.apps.helloServer.name }}
    spec:
      containers:
      - image: "{{ .Values.apps.helloServer.image.name }}:{{ .Values.apps.helloServer.image.tag }}"
        name: {{ .Values.apps.helloServer.name }}
        ports:
        - containerPort: {{ .Values.apps.helloServer.portData.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.helloServer.service.name }}
  labels:
    app: {{ .Values.apps.helloServer.name }}
    service: {{ .Values.apps.helloServer.service.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.apps.helloServer.portData.port }}
    targetPort: {{ .Values.apps.helloServer.portData.targetPort }}
  selector:
    app: {{ .Values.apps.helloServer.name }}