apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-route
  namespace: default
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.httpsListener.domainBased.nginx.name }}
  hostnames: 
    - {{ .Values.gateway.httpsListener.domainBased.nginx.hostname }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.apps.nginx.service.name }}
      port: {{ .Values.apps.nginx.portData.port }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-route
  namespace: default
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.httpsListener.domainBased.httpbin.name }}
  hostnames: 
    - {{ .Values.gateway.httpsListener.domainBased.httpbin.hostname }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.apps.httpbin.service.name }}
      port: {{ .Values.apps.httpbin.portData.port }}
    
