apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-http-redirect
  namespace: default
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.httpListener.name }}
  hostnames: 
    - {{ .Values.gateway.httpsListener.domainBased.nginx.hostname }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: httpbin-http-redirect
  namespace: default
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.httpListener.name }}
  hostnames: 
    - {{ .Values.gateway.httpsListener.domainBased.httpbin.hostname }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-http-redirect
  namespace: default
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
      sectionName: {{ .Values.gateway.httpListener.name }}
  hostnames: 
    - {{ .Values.gateway.httpsListener.pathBased.hostname }}
  rules:
    - filters:
      - type: RequestRedirect
        requestRedirect:
            scheme: https
            statusCode: 301