kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/cert-manager.yaml
kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/cert-issuer-staging.yaml
kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/cert-issuer-prod.yaml
kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/httproute.yaml
kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/httproute2.yaml
kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/gateway.yaml
kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/namespace.yaml
kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/httpbin.yaml
kubectl delete -f gateway/istio/micro-services/nginx_and_httpbin_https/nginx.yaml
