kubectl delete -f gateway/istio/https/cert-manager.yaml
kubectl delete -f gateway/istio/https/cert-issuer-staging.yaml
kubectl delete -f gateway/istio/https/cert-issuer-prod.yaml
kubectl delete -f gateway/istio/https/redirect_httproute.yaml
kubectl delete -f gateway/istio/https/httproute.yaml
kubectl delete -f gateway/istio/https/httproute2.yaml
kubectl delete -f gateway/istio/https/gateway.yaml
kubectl delete -f gateway/istio/https/namespace.yaml
kubectl delete -f gateway/istio/https/httpbin.yaml
kubectl delete -f gateway/istio/https/nginx.yaml
